package queries

// Code generated by sqlset-gen. DO NOT EDIT.
// Source: github.com/istovpets/sqlset.

// Generated by this command:
// go run github.com/istovpets/sqlset/cmd/sqlset-gen --dir=. --out=queries-gen.go --pkg=queries

// user.sql
var User = struct {
	Create string
	Delete string
	Get    string
	GetAll string
	Update string
}{
	Create: "user.Create",
	Delete: "user.Delete",
	Get:    "user.Get",
	GetAll: "user.GetAll",
	Update: "user.Update",
}
